FROM ubuntu:18.04

RUN echo "nameserver 208.67.222.222" | sudo tee /etc/resolvconf/resolv.conf.d/base > /dev/null
RUN apt-get update -y
RUN apt-get install -y git openssl curl unzip zip

ARG KUBE_PASSWORD
ARG AWS_KEY
ARG AWS_SECRET_KEY
ARG DOCKER_USERNAME
ARG DOCKER_PASSWORD
ARG CERTIFICATE_AUTHORITY_DATA
ARG CLIENT_CERTIFICATE_DATA
ARG CLIENT_KEY_DATA

RUN git clone https://github.com/bayoumi17m/Piazza.git

WORKDIR Piazza

COPY ./build_scripts/kube-secrets.txt /Piazza/deployment-setup/build_scripts/kube-secrets.txt

RUN chmod +x ./deployment-setup/build_scripts/install-dependencies.sh
RUN ./deployment-setup/build_scripts/install-dependencies.sh
RUN mv ./kubectl /usr/local/bin/kubectl

RUN mkdir ~/.kube
RUN mv ./deployment-setup/build_scripts/kubeconfig ~/.kube/config
RUN . ./deployment-setup/build_scripts/kube-secrets.txt
RUN export $(cut -d= -f1 ./deployment-setup/build_scripts/kube-secrets.txt)

RUN kubectl config set clusters.cs4300.k8s.mycourseindex.vpc.certificate-authority-data $CERTIFICATE_AUTHORITY_DATA
RUN kubectl config set users.cs4300.k8s.mycourseindex.vpc.client-certificate-data "$CLIENT_CERTIFICATE_DATA"
RUN kubectl config set users.cs4300.k8s.mycourseindex.vpc.client-key-data "$CLIENT_KEY_DATA"
RUN kubectl config set users.cs4300.k8s.mycourseindex.vpc.password "$KUBE_PASSWORD"
RUN kubectl config set users.cs4300.k8s.mycourseindex.vpc.net-basic-auth.password "$KUBE_PASSWORD"

RUN mkdir ~/.aws
RUN touch ~/.aws/credentials
RUN echo '[default]' >> ~/.aws/credentials
RUN echo "aws_access_key_id = $AWS_KEY">> ~/.aws/credentials
RUN echo "aws_secret_access_key = $AWS_SECRET_KEY" >> ~/.aws/credentials

RUN touch ~/.aws/config
RUN echo '[default]' >> ~/.aws/config
RUN echo "output = json">> ~/.aws/config
RUN echo "region = us-east-1" >> ~/.aws/config
# RUN chmod +x ./deployment-setup/build_scripts/inject-secrets.sh
# RUN chmod +x ./deployment-setup/build_scripts/deploy-k8s.sh

# RUN ./deployment-setup/build_scripts/inject-secrets.sh

RUN export GREEN='\033[0;32m'
RUN export NC='\033[0;0m'
RUN export PATH=$PATH:$(pwd)

RUN echo "nameserver 172.31.36.87" | tee -a /etc/resolv.conf
RUN echo -e "${GREEN}==== Testing kubectl connection ====${NC}"
RUN kubectl get nodes
RUN echo -e "${GREEN}==== Ending kubectl connection ====${NC}"
RUN echo ''
